
// Generated by Cadence Genus(TM) Synthesis Solution 21.17-s066_1
// Generated on: Dec 14 2025 11:45:38 EST (Dec 14 2025 16:45:38 UTC)

// Verification Directory fv/arithmetic_unit 

module full_adder(Ai, Bi, Cini, Di, Couti);
  input Ai, Bi, Cini;
  output Di, Couti;
  wire Ai, Bi, Cini;
  wire Di, Couti;
  wire n_2, n_3, n_4, n_5, n_6, n_7;
  OR2X1 g79__2398(.A (n_3), .B (n_5), .Y (n_7));
  CLKMX2X12 g80__5107(.A (Cini), .B (n_2), .S0 (n_4), .Y (n_6));
  AOI2BB1X1 g81__6260(.A0N (Ai), .A1N (Bi), .B0 (n_2), .Y (n_5));
  ADDHX1 g82__4319(.A (Ai), .B (Bi), .CO (n_3), .S (n_4));
  INVX1 g83(.A (Cini), .Y (n_2));
  CLKBUFX20 drc_bufs(.A (n_7), .Y (Couti));
  CLKBUFX20 drc_bufs84(.A (n_6), .Y (Di));
endmodule

module mux4to1(a, b, c, d, sel, out);
  input a, b, c, d;
  input [1:0] sel;
  output out;
  wire a, b, c, d;
  wire [1:0] sel;
  wire out;
  MX2XL g39__8428(.A (sel[1]), .B (sel[0]), .S0 (b), .Y (out));
endmodule

module arithmetic_unit(Ai, Bi, Cini, sel, Di, Couti);
  input Ai, Bi, Cini;
  input [1:0] sel;
  output Di, Couti;
  wire Ai, Bi, Cini;
  wire [1:0] sel;
  wire Di, Couti;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       mux_out;
  full_adder FA(.Ai (Ai), .Bi (mux_out), .Cini (Cini), .Di (Di), .Couti
       (Couti));
  mux4to1 MUX_B(.a (UNCONNECTED_HIER_Z), .b (Bi), .c
       (UNCONNECTED_HIER_Z0), .d (UNCONNECTED_HIER_Z1), .sel (sel),
       .out (mux_out));
endmodule

